export const BOOK_LIST_REQUIEST = 'BOOK_LIST_REQUiEST';
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS';
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL';

export const BOOK_DETAILS_REQUIEST = 'BOOK_DETAILS_REQUiEST';
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL';
